name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows
            os_short: win
          - os: macos
            os_short: mac
          - os: ubuntu
            os_short: linux
    runs-on: ${{ matrix.os }}-latest
    steps:
      - run: git config --global core.autocrlf false
        if: matrix.os == 'windows'
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
      - run: npm version
      - run: npm ci
      - run: npm run electron:build
      - run: node scripts/archive.mjs ${{ matrix.os_short }} ${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os}}-release
          path: dist/release-*.zip
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - uses: softprops/action-gh-release@a74c6b72af54cfa997e81df42d94703d6313a2d0 # v2.0.6
        with:
          files: dist/release-*.zip
          draft: true
